const iconMap={monitor:'▣',folder:'▰',chart:'▥',book:'▤',file:'▧',check:'✓',calendar:'◫',wallet:'◈',link:'↗',info:'i'};
export const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
export function header(current=''){const h=el('header','site-header');const inner=el('div','container header-inner');const brand=el('a','brand');brand.href='./index.html';const mark=el('span','brand-mark','P');const copy=el('span','brand-copy','PEPK Workspace');copy.append(el('small','', 'Dinas Kesehatan Kabupaten Kudus'));brand.append(mark,copy);const btn=el('button','menu-button','☰');btn.type='button';btn.setAttribute('aria-label','Buka navigasi');btn.setAttribute('aria-expanded','false');const nav=el('nav','nav');nav.setAttribute('aria-label','Navigasi utama');[['index.html','Beranda','home'],['workspace.html','Ruang Kerja','workspace'],['resources.html','Pustaka','resources'],['information.html','Informasi','information'],['about.html','Tentang','about']].forEach(([href,label,key])=>{const a=el('a','',label);a.href=`./${href}`;if(current===key)a.setAttribute('aria-current','page');nav.append(a)});btn.addEventListener('click',()=>{const open=nav.dataset.open!=='true';nav.dataset.open=String(open);btn.setAttribute('aria-expanded',String(open))});inner.append(brand,btn,nav);h.append(inner);return h}
export function footer(version='0.1.0',updated='17 Juli 2026'){const f=el('footer','site-footer');const g=el('div','container footer-grid');const a=el('div');a.append(el('div','footer-title','PEPK Workspace'),el('div','footer-copy','Sub Bagian Perencanaan, Evaluasi, Pelaporan dan Keuangan'),el('div','footer-copy','Dinas Kesehatan Kabupaten Kudus'));const b=el('div','footer-meta');b.append(el('div','',`Versi ${version}`),el('div','',`Data diperbarui ${updated}`),el('div','', '© 2026 PEPK – Dinas Kesehatan Kabupaten Kudus'));g.append(a,b);f.append(g);return f}
export function resourceCard(r){const a=el('a','card');a.href=r.url||'#';if(r.open_mode==='new_tab'||/^https?:/.test(r.url||'')){a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',`${r.title} (terbuka di tab baru)`)}a.append(el('div','card-icon',iconMap[r.icon]||iconMap.file),el('h3','',r.title),el('p','',r.description||'Buka resource pekerjaan.'));const meta=el('div','card-meta');meta.append(el('span','badge',r.type||'resource'),el('span','muted','Buka ↗'));a.append(meta);return a}
export function workspaceCard(w,count=0){const a=el('a','card');a.href=`./workspace.html?id=${encodeURIComponent(w.id)}`;a.append(el('div','card-icon',iconMap[w.icon]||'◫'),el('h3','',w.title),el('p','',w.description));const m=el('div','card-meta');m.append(el('span','badge',`${count} resource`),el('span','muted','Lihat →'));a.append(m);return a}
export function infoCard(i){const a=el('a','card info-card');a.href=`./information.html?id=${encodeURIComponent(i.id)}`;a.append(el('time','', 'Informasi PEPK'),el('h3','',i.title),el('p','',i.summary||i.content||''));return a}
export function status(message,type=''){return el('div',`status ${type?`status--${type}`:''}`,message)}
export function mountShell(current,main,updated){const shell=el('div','site-shell');const skip=el('a','skip-link','Lewati ke konten');skip.href='#main-content';main.id='main-content';main.classList.add('site-main');shell.append(skip,header(current),main,footer('0.1.0',updated));document.body.replaceChildren(shell)}
